name: deploy website

on:
  push:
    branches:
     - master
jobs:
   deploy:
     runs-on: ubuntu-lastest
     steps:
     - name: Checkout
       uses: action/checkout@v1
     - name: configure-aws-credentials
       uses: aws-action/configure-aws-credential@v1
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESSS_KEY_ID }}
         aws-secrets-access-key: ${{ secrets.AWS_SECRETS_ACCESS_KEY }}
         aws-region: us-east-1
     - name: Deploy static sits to S3 bucket
       run: aws s3 sync . s3://website-bucket-task1  --delete
